In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"##last

- built-in type : List 
- Arrays/Matrices (Numpy)

#### No copy

In [51]:
import numpy as np
a=np.arange(6)
b=a
print(a);print(b)
id(a);id(b) 

[0 1 2 3 4 5]
[0 1 2 3 4 5]


4647851392

4647851392

In [55]:
b.shape=3,2
b;a

array([[-100, -100],
       [   2,    3],
       [   4,    5]])

array([[-100, -100],
       [   2,    3],
       [   4,    5]])

#### Shallow copy (view)

In [83]:
import numpy as np
a=np.arange(6).reshape(3,2);b=a.view()
id(a);id(b)
b.shape=2,3
a;b

4648383952

4648383392

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

#### Shallow copy (view)

In [82]:
a=np.arange(6).reshape(3,2)
b=a.view()
a;b
b[0,0]=-100
a;b

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[0, 1],
       [2, 3],
       [4, 5]])

array([[-100,    1],
       [   2,    3],
       [   4,    5]])

array([[-100,    1],
       [   2,    3],
       [   4,    5]])

#### Shallow copy: view
- A slicing operation creates a view 

In [84]:
a=np.array([[10,10],[2,3],[4,5]])
s=a[:,:2]
a;s
s[0,0]=100
s.shape=2,3
s;a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

array([[100,  10,   2],
       [  3,   4,   5]])

array([[100,  10],
       [  2,   3],
       [  4,   5]])

#### Shallow copy: view

In [4]:
import numpy as np
a=np.array([[10,10],[2,3],[4,5]])
s=a.view()
a;s
s[0]=100
s.shape=2,3
s;a

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

array([[100, 100,   2],
       [  3,   4,   5]])

array([[100, 100],
       [  2,   3],
       [  4,   5]])

#### deep copy

In [50]:
import numpy as np
a=np.array([[10,10],[2,3],[4,5]])
print(a)
b=a.copy()
id(a);id(b)
b[0,0]=100
b;a

[[10 10]
 [ 2  3]
 [ 4  5]]


4647851632

4648311104

array([[100,  10],
       [  2,   3],
       [  4,   5]])

array([[10, 10],
       [ 2,  3],
       [ 4,  5]])

- No copy: `b=a`
- Shallow copy:`b=a[:]`
- deep copy:`b=np.copy(a)`