In [31]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"##last

## Array and Matrices: Numpy

![](http://www.wizdomhub.com/wp-content/uploads/2017/08/numpy_project_page.jpg)

- built-in library (standard)
- third party library

In [4]:
from math import *
pi

3.141592653589793

NumPy is short for **Numeric Python**. It's the fundamental package for scientific computing with Python. Numpy provides the core data type for econometrics,statistics, and numerical analysis.
  - a powerful N-dimensional array object: **array oriented computing**
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities


* anaconda have **MKL **(math kernal library) by default (**BLAS**: basic linear algebra subprograms)
  - optimized math (linear algebra) routines

<https://software.intel.com/en-us/mkl>

In [5]:
! conda list numpy
## conda search numpy

# packages in environment at /anaconda:
#
numpy                     1.11.3                   py35_0  
numpy                     1.13.3                    <pip>
numpydoc                  0.7.0                    py35_0  


- **Arrays**
- **Matrices**


- 1\.  Dimensions
- 2\.  Mathematical operations: *element-by-element* vs. *linear algebra*
- 3\.  arrays are more common than matrices
- 4\.  Convert array to matrix: `mat` or `asmatrix`

#### import library

In [29]:
import numpy as np


3.141592653589793

#### array

- base data type in Numpy
- homogeneous
- rectangular

#### array
- np.shape
- np.dtype

#### array
- **np.shape**
- np.dtype

- arrays: shape 1 dimension


In [42]:
x=[0.0,1,2,3,54]
a=np.array(x)
a.shape
a.ndim

(5,)

1

In [43]:
type(a)

numpy.ndarray

- arrays
shape: 2 dimensions


In [46]:
b=np.array([[0.0,1,1,2,4],[5,6,7,8,9]])### rectangular

In [47]:
b

array([[ 0.,  1.,  1.,  2.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [48]:
type(b)

numpy.ndarray

In [49]:
b.ndim
b.shape

2

(2, 5)

In [ ]:
b=np.array([[0.0,1,1,2,4],[5,6,7,8,9]])
b.shape

#### array
- **np.shape**
- np.dtype

In [51]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c
c.ndim
c.shape

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

3

(2, 2, 2)

#### array
- **np.shape**: 1 dimension, 2 dimensions, 3 dimensions...
- np.dtype

#### array
- np.shape
- **np.dtype**

- arrays: **dtype**

In [55]:
d=np.array(np.arange(5.0))
##d=[0,1,2,3,4]##integers
d=np.array(d)
d
d.dtype

array([ 0.,  1.,  2.,  3.,  4.])

dtype('float64')

- arrays: **dtype**

In [56]:
e=[0.0,1,2,3,4]##float
e=np.array(e)
e
e.dtype

array([ 0.,  1.,  2.,  3.,  4.])

dtype('float64')

- arrays: **dtype**

In [57]:
f=[1,2,43,5+1j]#### array
f=np.array(f)
f.dtype

dtype('complex128')

#### array
- np.shape
- np.dtype

#### matrix

In [58]:
y=np.array([0.0,1,2,4,5])
y*y ##element-by-element

In [60]:
z=np.asmatrix(y)
type(z)
z.shape

numpy.matrixlib.defmatrix.matrix

(1, 5)

In [63]:
z*z.T

matrix([[ 46.]])

$$\mathbf{X} = \left[\begin{array}
{rrrr}
0.0 & 1.0 & 2.0 & 4.0 & 5.0 
\end{array}\right]
$$

#### Arrays

- 1-Dimensional arrays
- 2-Dimensional arrays
- Multidimensional arrays

#### 1-Dimensional arrays

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 & 5 
\end{array}\right]
$$

In [69]:
x=np.array(range(5))

In [68]:
x.ndim
x.shape
## x@x

2

(1, 5)

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 & 5 
\end{array}\right]
$$

In [70]:
x=np.array([[1,2,3,4,5]])
x
x.ndim
x.shape

array([[1, 2, 3, 4, 5]])

2

(1, 5)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/c6f7cdbe9cd36a436b0e5304ea2b42d640203777)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/5f877a81f2a22a2109790c35f6c11bf85af22b82)

In [75]:
x;x.shape
x@x.T;x.T@x

array([[1, 2, 3, 4, 5]])

(1, 5)

array([[55]])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [ ]:
y=np.matrix([1,2,3,4,5])
y.shape
type(y)

In [ ]:
y@y.T

$$\mathbf{Y} = \left[\begin{array}
{r}
1 \\
2 \\
3 \\
4 \\
5
\end{array}\right]
$$

In [77]:
x=np.matrix([[1],[2],[3],[4],[5]])
x.shape
x.ndim

(5, 1)

2

In [78]:
y=np.array([[1],[2],[3],[4],[5]])
y.shape

(5, 1)

In [79]:
x=np.array([[1,2,3,4,5]])
x.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

#### 2-Dimensional arrays

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6 \\
7 & 8 & 9  
\end{array}\right]
$$

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x
x.shape

#### Multidimensional Arrays

In [ ]:
np.zeros((2,2,3))
np.empty((2,2,2))

#### concatenation

$$\mathbf{x} = \left[\begin{array}
{r}
1 & 2   \\
3 & 4  
\end{array}\right]
$$

$$\mathbf{y} = \left[\begin{array}
{r}
5 & 6   \\
7 & 8  
\end{array}\right]
$$


$$\mathbf{z} = \left[\begin{array}
{r}
x  \\
y 
\end{array}\right]
$$

<img src="https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png"
style="width:720px;height:402.5px;float:middle">

In [85]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [86]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [89]:
z=np.concatenate((x,y),axis=0)#### concatenation
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### concatenation

In [ ]:
np.vstack((x,y))

In [ ]:
np.hstack((x,y))

#### Accessing elements of an array


- **1**\. **Scalar selection**: output reduces to scalar
- **2**\. **Array slicing**





- **Scalar selection**

<img src="https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png"
style="width:372.5px;height:331.5px;float:middle">

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3 & 4 & 5  
\end{array}\right]
$$

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
x[0]

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6   
\end{array}\right]
$$

In [90]:
y=np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
y[1,2]

6

In [92]:
type(y[1,2])  ##scarlar 纯量

numpy.int64

In [96]:
y[0]=-5

In [97]:
y

array([[-5, -5, -5],
       [ 4,  5,  6]])

- **Array slicing**

- s is the stride

| short version |   long version |
|:------:|:------:|:------:|
|: ::|**0:n:1**|
| a: a:n|a:n:1|
|  :b|0:b:1|
| ::s|0:n:s|




####  **Array slicing**
- 1 dimensional arrays

In [98]:
x=np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [99]:
y=x[:]
y

array([1, 2, 3, 4, 5])

In [100]:
y=x[:2]
y

array([1, 2])

In [101]:
y=x[1::2]
y

array([2, 4])

####  **Array slicing**
- 2 dimensional arrays



| short version |   long version |
|:------:|:------:|:------:|
|y[a:b,c:d]|[a:b,:],[:,c:d]|
|y[a:b]|y[a:b,:]|


####  **Array slicing**
- 2 dimensional arrays

In [102]:
y=np.array([[0,1,2,3,4],[5,6,7,8,9]])
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
y[:1,:]

array([[0, 1, 2, 3, 4]])

In [104]:
y[:1]

array([[0, 1, 2, 3, 4]])

In [106]:
y[:,:1]

array([[0],
       [5]])

In [ ]:
y[:1,0:3]

In [ ]:
y[:1,:][:,0:3]

In [ ]:
y[:,3:]

####  **Array slicing**
- 3 dimensional arrays

<img src="https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png"
style="width:720px;height:402.5px;float:middle">

In [108]:
y=np.array([[[1,2],[4,3]],[[2,7],[9,8]]])
y

array([[[1, 2],
        [4, 3]],

       [[2, 7],
        [9, 8]]])

In [109]:
y[0,:,:]
y[:,0,:]
y[:,:,0]
y[0,:,0]

array([[1, 2],
       [4, 3]])

array([[1, 2],
       [2, 7]])

array([[1, 4],
       [2, 9]])

array([1, 4])

#### Mixed selection using scalar and slice selector

In [ ]:
x=np.array([[1,2],[3,4]])
x

In [ ]:
x[:1,:]
x[0,:]###it's the best practice for single column or row.


#### mixed selection example

In [ ]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
x

In [ ]:
x[:1,:]  ##preserve the 2 dimensions

In [ ]:
x[0,:] ### reduce to 1-d array.

In [ ]:
x[0,0]  ###scarlar

In [ ]:
x[:,0] ### reduce to 1-d array

#### assignment using slicing

In [ ]:
[[0.0]*3]*3
x=np.array([[0.0]*3]*3)
x

In [ ]:
x[0,:]=np.array([1,2,3])
x

#### assignment using slicing

In [ ]:
x[::2,::2]#### assignment using slicing

In [ ]:
x[::2,::2]=np.array([[-99,-99],[-99,-99]])
x

In [ ]:
x[1,1]=math.pi
x

#### assignment using slicing
- truncated the data by default

In [ ]:
y=np.array(np.arange(5.0))
y.dtype

In [ ]:
y[0]=math.pi
y

#### Linear slicing using `flat`

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6 \\
7 & 8 & 9  
\end{array}\right]
$$

#### Linear slicing using `flat`

In [213]:
y=np.reshape(np.arange(25),(5,5))
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [221]:
y[0]

array([0, 1, 2, 3, 4])

In [222]:
y[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [223]:
y.flat[6]

6

In [224]:
y.flat[12:15]

array([12, 13, 14])