In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"##last

## Array and Matrices: Numpy

![](http://www.wizdomhub.com/wp-content/uploads/2017/08/numpy_project_page.jpg)

- built-in library (standard)
- third party library

In [4]:
from math import *
pi

3.141592653589793

NumPy is short for **Numeric Python**. It's the fundamental package for scientific computing with Python. Numpy provides the core data type for econometrics,statistics, and numerical analysis.
  - a powerful N-dimensional array object: **array oriented computing**
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities


* anaconda have **MKL **(math kernal library) by default (**BLAS**: basic linear algebra subprograms)
  - optimized math (linear algebra) routines

<https://software.intel.com/en-us/mkl>

In [ ]:
! conda list numpy
## conda search numpy

- **Arrays**
- **Matrices**


- 1\.  Dimensions
- 2\.  Mathematical operations: *element-by-element* vs. *linear algebra*
- 3\.  arrays are more common than matrices
- 4\.  Convert array to matrix: `mat` or `asmatrix`

#### import library

In [ ]:
import numpy as np


#### array

- base data type in Numpy
- homogeneous
- rectangular

#### array
- np.shape
- np.dtype

#### array
- **np.shape**
- np.dtype

- arrays: shape 1 dimension


In [ ]:
import numpy as np
x=[[0.0,1,2,3,54],[1,2,3,4,5]]
a=np.array(x)
a.ndim
a.shape


In [ ]:
type(a)

- arrays
shape: 2 dimensions


In [ ]:
b=np.array([[0.0,1,1,2,4],[5,6,7,8,9]])### rectangular

In [ ]:
b

In [ ]:
type(b)

In [ ]:
b.ndim
b.shape

In [ ]:
b=np.array([[0.0,1,1,2,4],[5,6,7,8,9]])
b.shape

#### array
- **np.shape**
- np.dtype

In [ ]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c
c.ndim
c.shape

#### array
- **np.shape**: 1 dimension, 2 dimensions, 3 dimensions...
- np.dtype

#### array
- np.shape
- **np.dtype**

- arrays: **dtype**

In [ ]:
d=np.array(np.arange(5.0))
##d=[0,1,2,3,4]##integers
d=np.array(d)
d
d.dtype

- arrays: **dtype**

In [ ]:
e=[0.0,1,2,3,4]##float
e=np.array(e)
e
e.dtype

- arrays: **dtype**

In [ ]:
f=[1,2,43,5+1j]#### array
f=np.array(f)
f.dtype

#### array
- np.shape
- np.dtype

#### matrix

In [11]:
y=np.array([0.0,1,2,4,5])
y*y ##element-by-element

array([  0.,   1.,   4.,  16.,  25.])

In [16]:
z=np.asmatrix(y)
type(z)
z.shape

(1, 5)

In [17]:
z*z.T

matrix([[ 46.]])

$$\mathbf{X} = \left[\begin{array}
{rrrr}
0.0 & 1.0 & 2.0 & 4.0 & 5.0 
\end{array}\right]
$$

#### Arrays

- 1-Dimensional arrays
- 2-Dimensional arrays
- Multidimensional arrays

#### 1-Dimensional arrays

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 & 5 
\end{array}\right]
$$

In [ ]:
x=np.array(range(5))

In [ ]:
x.ndim
x.shape
## x@x

$$\mathbf{X} = \left[\begin{array}
{rrrr}
1 & 2 & 3 & 4 & 5 
\end{array}\right]
$$

In [14]:
x=np.array([[1,2,3,4,5]])
x
x.ndim
x.shape

array([[1, 2, 3, 4, 5]])

2

(1, 5)

In [15]:
x;x.shape
x@x.T;x.T@x

array([[1, 2, 3, 4, 5]])

(1, 5)

array([[55]])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [16]:
y=np.matrix([1,2,3,4,5])
y.shape
type(y)

(1, 5)

numpy.matrixlib.defmatrix.matrix

In [18]:
y@y.T
y.T@y

matrix([[55]])

matrix([[ 1,  2,  3,  4,  5],
        [ 2,  4,  6,  8, 10],
        [ 3,  6,  9, 12, 15],
        [ 4,  8, 12, 16, 20],
        [ 5, 10, 15, 20, 25]])

$$\mathbf{Y} = \left[\begin{array}
{r}
1 \\
2 \\
3 \\
4 \\
5
\end{array}\right]
$$

In [19]:
x=np.matrix([[1],[2],[3],[4],[5]])
x.shape
x.ndim

(5, 1)

2

In [20]:
y=np.array([[1],[2],[3],[4],[5]])
y.shape

(5, 1)

In [21]:
x=np.array([[1,2,3,4,5]])
x.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

#### 2-Dimensional arrays

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6 \\
7 & 8 & 9  
\end{array}\right]
$$

In [22]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x
x.shape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(3, 3)

#### Multidimensional Arrays

In [ ]:
np.zeros((2,2,3))
np.empty((2,2,2))

#### Dimension transformation

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3 & 4 & 5  
\end{array}\right]
$$

In [18]:
xs = np.array([1, 2, 3, 4, 5])
xs.shape

(5,)

In [19]:
xs[:, np.newaxis].shape  # a matrix with only one column
xs[np.newaxis, :].shape  # a matrix with only one row

(1, 5)

In [20]:
xs[:, np.newaxis, np.newaxis].shape  # a 3 dimensional array
np.squeeze(xs[:, np.newaxis, np.newaxis]).shape

(5,)

#### concatenation

$$\mathbf{x} = \left[\begin{array}
{r}
1 & 2   \\
3 & 4  
\end{array}\right]
$$

$$\mathbf{y} = \left[\begin{array}
{r}
5 & 6   \\
7 & 8  
\end{array}\right]
$$


$$\mathbf{z} = \left[\begin{array}
{r}
x  \\
y 
\end{array}\right]
$$

<img src="https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png"
style="width:720px;height:402.5px;float:middle">

In [6]:
import numpy as np
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [7]:
y=np.array([[5,6],[7,8]])
y

array([[5, 6],
       [7, 8]])

In [8]:
z=np.concatenate((x,y),axis=0)#### concatenation
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### concatenation

In [9]:
np.vstack((x,y))  

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [10]:
np.hstack((x,y))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Accessing elements of an array


- **1**\. **Scalar selection**: output reduces to scalar
- **2**\. **Array slicing**





- **Scalar selection**

<img src="https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png"
style="width:372.5px;height:331.5px;float:middle">

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3 & 4 & 5  
\end{array}\right]
$$

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
x[0]

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6   
\end{array}\right]
$$

In [ ]:
y=np.array([[1,2,3],[4,5,6]])

In [ ]:
y[1,2]

In [ ]:
type(y[1,2])  ##scarlar 纯量

In [ ]:
y[0]=-5

In [ ]:
y

- **Array slicing**

- s is the stride

| short version |   long version |
|:------:|:------:|:------:|
|: ::|**0:n:1**|
| a: a:n|a:n:1|
|  :b|0:b:1|
| ::s|0:n:s|




####  **Array slicing**
- 1 dimensional arrays

In [24]:
x=np.array([1,2,3,4,5])

In [25]:
y=x[:]
y

array([1, 2, 3, 4, 5])

In [26]:
y=x[:2]
y

array([1, 2])

In [27]:
y=x[1::2]
y

array([2, 4])

####  **Array slicing**
- 2 dimensional arrays



| short version |   long version |
|:------:|:------:|:------:|
|y[a:b,c:d]|[a:b,:],[:,c:d]|
|y[a:b]|y[a:b,:]|


####  **Array slicing**
- 2 dimensional arrays

In [28]:
y=np.array([[0,1,2,3,4],[5,6,7,8,9]])
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
y[:1,:]

array([[0, 1, 2, 3, 4]])

In [30]:
y[:1]

array([[0, 1, 2, 3, 4]])

In [31]:
y[:,:1]

array([[0],
       [5]])

In [ ]:
y[:1,0:3]

In [ ]:
y[:1,:][:,0:3]

In [34]:
y[:,3:]

array([[3, 4],
       [8, 9]])

####  **Array slicing**
- 3 dimensional arrays

<img src="https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png"
style="width:720px;height:402.5px;float:middle">

In [35]:
y=np.array([[[1,2],[4,3]],[[2,7],[9,8]]])
y

array([[[1, 2],
        [4, 3]],

       [[2, 7],
        [9, 8]]])

In [36]:
y[0,:,:]
y[:,0,:]
y[:,:,0]
y[0,:,0]

array([[1, 2],
       [4, 3]])

array([[1, 2],
       [2, 7]])

array([[1, 4],
       [2, 9]])

array([1, 4])

#### Mixed selection using scalar and slice selector

In [44]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [45]:
x[:1,:]
x[0,:]###it's the best practice for single column or row.


array([[1, 2]])

array([1, 2])

#### mixed selection example
 - pure slicing
 - mixed slicing
 - puer scalar selection

In [66]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
x[:1,:]  ##preserve the 2 dimensions

array([[0, 1, 2, 3, 4]])

In [53]:
x[0,:] ### reduce to 1-d array.

array([0, 1, 2, 3, 4])

In [54]:
x[0,0]  ###scarlar

0

In [48]:
x[:,0] ### reduce to 1-d array

array([0, 5])

#### assignment using slicing

In [70]:
x=np.array([[0.0]*3]*3)
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [71]:
x[0,:]=np.array([1,2,3])
x

array([[ 1.,  2.,  3.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### assignment using slicing

In [77]:
x[::2,::2]#### assignment using slicing


array([[-99., -99.],
       [-99., -99.]])

In [78]:
x[::2,::2]=np.array([[-99,-99],[-99,-99]])
x

array([[-99.,   2., -99.],
       [  0.,   0.,   0.],
       [-99.,   0., -99.]])

In [80]:
import math
x[1,1]=math.pi
x

array([[-99.        ,   2.        , -99.        ],
       [  0.        ,   3.14159265,   0.        ],
       [-99.        ,   0.        , -99.        ]])

#### assignment using slicing
- truncated the data by default

In [82]:
y=np.array(np.arange(5.0))
y.dtype

dtype('float64')

In [83]:
y[0]=math.pi
y

array([ 3.14159265,  1.        ,  2.        ,  3.        ,  4.        ])

#### Linear slicing using `flat`

$$\mathbf{X} = \left[\begin{array}
{r}
1 & 2 & 3  \\
4 & 5 & 6 \\
7 & 8 & 9  
\end{array}\right]
$$

#### Linear slicing using `flat`

In [ ]:
y=np.reshape(np.arange(25),(5,5))
y

In [ ]:
y[0]

In [ ]:
y[6]

In [ ]:
y.flat[6]

In [ ]:
y.flat[12:15]